// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var HelloWorld$LearnReason = require("../src/HelloWorld.bs.js");

Jest.describe("HelloWorld", (function (param) {
        return Jest.test("sayHelloWorld", (function (param) {
                      var result = HelloWorld$LearnReason.sayHelloWorld(/* () */0);
                      return Jest.Expect.toBe("Hello world!", Jest.Expect.expect(result));
                    }));
      }));

/*  Not a pure module */
